# MySQL address, user and password
# user must have replication privilege in MySQL.
my_addr = "47.100.10.111:3306"
my_user = "root"
my_pass = "Ttouch2016"
my_charset = "utf8"

# Set true when elasticsearch use https
#es_https = false
# Elasticsearch address
es_addr = "47.101.4.173:9200"
# Elasticsearch user and password, maybe set by shield, nginx, or x-pack
# Path to store data, like master.info, if not set or empty,
# we must use this to support breakpoint resume syncing.
# TODO: support other storage, like etcd.
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# if we have no privilege to use mysqldump with --master-data,
# we must skip it.
#skip_master_data = false

# minimal items to be inserted in one bulk
bulk_size = 128

# force flush the pending requests if we don't have enough items >= bulk_size
flush_bulk_time = "200ms"

# Ignore table without primary key
skip_no_pk_table = false

[[source]]
schema = "shop"
tables = ["ty_shop","ty_employee"]

[[rule]]
schema = "shop"
table = "ty_shop"
index = "shop"
type = "shop"
[rule.field]
created_at=",time"
updated_at=",time"

[[rule]]
schema = "shop"
table = "ty_employee"
index = "shop"
type = "shop"
nested = "shop_id"
[rule.field]
